--Part – A: 
--1. Update SPI of all students from 7.00 to 8.00. 
	UPDATE STUDENT SET SPI=8.00
	WHERE SPI=7.00
	SELECT * FROM STUDENT

--2. Change city of HETVI from RAJKOT to AHMEDABAD.
	UPDATE STUDENT SET CITY='AHMEDABAD'
	WHERE SNAME='HETVI' 
	SELECT * FROM STUDENT

--3. Update SPI of DEEP to 9.20 and city to VADODARA.
	UPDATE STUDENT SET SPI=9.20,CITY='VADODARA'
	WHERE SNAME='DEEP'
	SELECT * FROM STUDENT

--4. Update SPI of DHARMIK to 8.50. 
	UPDATE STUDENT SET SPI=8.50
	WHERE SNAME='DHARMIK'
	SELECT * FROM STUDENT

--5. Update branch name from COMPUTER to IT. 
	UPDATE STUDENT SET BRANCH='IT'
	WHERE BRANCH='COMPUTER'
	SELECT * FROM STUDENT

--6. Update branch of RAJ to AUTOMOBILE. 
	UPDATE STUDENT SET BRANCH='AUTOMOBILE'
	WHERE SNAME='RAJ'
	SELECT * FROM STUDENT

--7. Update SPI to 7.50 where STDID is between 103 and 107. 
	UPDATE STUDENT SET SPI=7.50
	WHERE STDID BETWEEN 103 AND 107
	SELECT * FROM STUDENT

--8. Update city of PARAG to MUMBAI.
	UPDATE STUDENT SET CITY='MUMBAI'
	WHERE SNAME='PARAG'
	SELECT * FROM STUDENT

--9. Update SPI of RIYA to 6.00. 
	UPDATE STUDENT SET SPI=6.00
	WHERE SNAME='RIYA'
	SELECT * FROM STUDENT

--10. Update SPI of SMAIR to 7.20 and branch to ELECTRICAL. 
	UPDATE STUDENT SET SPI=7.20,BRANCH='ELECTRICAL'
	WHERE SNAME='SMAIR'
	SELECT * FROM STUDENT

--Part – B: 
--11. Give 10% increment in SPI.
	UPDATE STUDENT SET SPI=(SPI+SPI*0.1)
	SELECT * FROM STUDENT

--12. Increase SPI by 20% for all students.  
	UPDATE STUDENT SET SPI=(SPI+SPI*0.2)
	SELECT * FROM STUDENT

--13. Increase SPI by 0.50 in all records.
	UPDATE STUDENT SET SPI=(SPI+SPI*0.05)
	SELECT * FROM STUDENT

--14. Update branch to 'EC' and SPI to 8.00 and city to Surat where SNAME is KRUNAL.
	UPDATE STUDENT SET BRANCH='EC',SPI=8.00,CITY='SURAT'
	WHERE SNAME='KRUNAL'
	SELECT * FROM STUDENT

--15. Update city to 'RAJKOT' and SPI to 7.00 where branch is CIVIL and stdid is less than 105. 
	UPDATE STUDENT SET CITY='RAJKOT',SPI=7.00
	WHERE BRANCH='CIVIL' AND STDID>105
	SELECT * FROM STUDENT

--Part – C: 
--16. Update SPI of student with stdid 110 to NULL. 
	UPDATE STUDENT SET SPI = NULL
	WHERE STDID=110
	SELECT * FROM STUDENT

--17. Update branch of VISHAL to NULL.
	UPDATE STUDENT SET BRANCH = NULL
	SELECT * FROM STUDENT

--18. Display names of students whose SPI is NULL.
	SELECT SNAME FROM STUDENT
	WHERE SPI IS NULL
	SELECT * FROM STUDENT

--19. Display students who have branch assigned.
	SELECT SNAME FROM STUDENT
	WHERE NOT BRANCH IS NULL
	SELECT * FROM STUDENT

--20. Update student with stdid 108 to name DARSHAN, branch COMPUTER, and SPI 8.50.  
	UPDATE STUDENT SET SNAME='DARSHAN',BRANCH='COMPUTER',SPI=8.50
	WHERE STDID=108
	SELECT * FROM STUDENT

--21. Update city to SURAT where SPI is less than 7.00.
	UPDATE STUDENT SET CITY='SURAT'
	WHERE SPI>7.00
	SELECT * FROM STUDENT

--22. Update city to NULL and branch to MECHANICAL where stdid is 109. 
	UPDATE STUDENT SET CITY=NULL,BRANCH='MECHANICAL'
	WHERE STDID=109
	SELECT * FROM STUDENT
